# Generated by Django 5.1.2 on 2024-11-13 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Признак активной задачи"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_related",
            field=models.BooleanField(
                default=False, verbose_name="Признак связанной задачи"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent",
                to="tracker.task",
                verbose_name="Родительская задача",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tracker.employee",
                verbose_name="Исполнитель задачи",
            ),
        ),
    ]
